---
deployment:
  tasks:
    - test -f frontend/dist/index.html || (echo "Missing dist build in repo" && exit 1)
    - /bin/rm -rf /home/qqgbtymm/public_html/assets
    - /bin/rm -f /home/qqgbtymm/public_html/index.html
    - /bin/rm -f /home/qqgbtymm/public_html/vite.svg
    - /bin/cp -R frontend/dist/* /home/qqgbtymm/public_html/
