---
deployment:
  tasks:
    - /bin/rm -rf /home/qqgbtymm/public_html/assets
    - /bin/rm -f /home/qqgbtymm/public_html/index.html
    - /bin/rm -f /home/qqgbtymm/public_html/vite.svg
    - /bin/cp -R frontend/dist/* /home/qqgbtymm/public_html/
