---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qqgbtymm/public_html
    - /bin/rm -rf $DEPLOYPATH/assets
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/rm -f $DEPLOYPATH/vite.svg
    - /bin/cp -R frontend/dist/* $DEPLOYPATH/
